import { StyleSheet } from 'react-native'

import { DESIGN_HEIGHT, DESIGN_WIDTH } from './onboarding.constants'

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  canvas: {
    position: 'absolute',
    width: DESIGN_WIDTH,
    height: DESIGN_HEIGHT,
    overflow: 'hidden',
  },
  fill: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  hero: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: DESIGN_WIDTH,
    height: 438,
  },
  logoPosition: {
    position: 'absolute',
    top: 72,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 20,
  },
  logoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 12,
    paddingRight: 20,
    height: 56,
    borderRadius: 28,
    gap: 6,
  },
  logo: {
    width: 42,
    height: 46,
  },
  logoName: {
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  bottomPanel: {
    position: 'absolute',
    top: 401,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  scene: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  card: {
    position: 'absolute',
    top: 432,
    left: 24,
    width: 326,
    borderRadius: 23,
    borderWidth: 1,
    padding: 17,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  groomingCard: {
    height: 144,
  },
  bookingCard: {
    height: 176,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    overflow: 'hidden',
    marginRight: 13,
  },
  avatarImage: {
    width: 100,
    height: 116,
    left: -11,
    top: -28,
  },
  smallAvatar: {
    width: 33,
    height: 33,
    borderRadius: 17,
    overflow: 'hidden',
    marginRight: 9,
  },
  smallAvatarImage: {
    width: 66,
    height: 76,
    left: -8,
    top: -18,
  },
  cardHeading: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  cardSubtitle: {
    marginTop: 5,
    fontSize: 13,
  },
  serviceIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 7,
  },
  progressTrack: {
    height: 5,
    width: 290,
    borderRadius: 3,
    overflow: 'hidden',
    marginTop: 17,
  },
  progressFill: {
    width: 290,
    height: 5,
    borderRadius: 3,
  },
  serviceList: {
    flexDirection: 'row',
    marginTop: 11,
    gap: 6,
  },
  serviceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 9,
    height: 27,
    gap: 4,
  },
  chipLabel: {
    fontSize: 11,
    fontWeight: '800',
  },
  sceneTitle: {
    position: 'absolute',
    top: 638,
    left: 20,
    right: 20,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.55,
  },
  groomingTitle: {
    top: 605,
  },
  salonTitle: {
    fontSize: 13,
    fontWeight: '900',
  },
  salonSubtitle: {
    fontSize: 10,
    marginTop: 4,
  },
  todayBadge: {
    paddingVertical: 5,
    paddingHorizontal: 7,
    borderRadius: 7,
    marginLeft: 5,
  },
  todayText: {
    fontSize: 10,
    fontWeight: '800',
  },
  timeLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 21,
    marginBottom: 8,
  },
  hours: {
    flexDirection: 'row',
    gap: 9,
  },
  hour: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourText: {
    fontSize: 16,
    fontWeight: '900',
  },
  hourSelected: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmationCard: {
    height: 158,
    top: 442,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
  },
  confirmationIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 9,
  },
  confirmationTitle: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  confirmationSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 5,
  },
  stepper: {
    position: 'absolute',
    top: 707,
    left: 18,
    right: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  stepperLine: {
    position: 'absolute',
    left: 32,
    right: 32,
    top: 15,
    height: 3,
    overflow: 'hidden',
  },
  stepperLineFill: {
    width: 274,
    height: 3,
  },
  step: {
    width: 64,
    alignItems: 'center',
  },
  stepCircle: {
    width: 33,
    height: 33,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeStep: {
    position: 'absolute',
    top: -1,
    left: -1,
    width: 33,
    height: 33,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '800',
    marginTop: 7,
  },
  confirmationPill: {
    position: 'absolute',
    top: 376,
    left: 44,
    width: 286,
    height: 59,
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    zIndex: 2,
  },
  pillIcon: {
    width: 31,
    height: 31,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  pillSubtitle: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
  },
  finalContent: {
    position: 'absolute',
    top: 454,
    left: 24,
    right: 24,
    bottom: 8,
  },
  finalTitle: {
    fontSize: 30,
    lineHeight: 33,
    fontWeight: '900',
    letterSpacing: -0.9,
    textAlign: 'center',
  },
  finalDescription: {
    marginTop: 16,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    letterSpacing: -0.25,
  },
  features: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 30,
  },
  feature: {
    flex: 1,
    height: 114,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
  },
  featureImage: {
    width: '100%',
    height: 61,
  },
  featureLabel: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 3,
  },
  startContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  startButton: {
    height: 55,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  startText: {
    fontSize: 18,
    fontWeight: '900',
  },
})
